const state = {
  initialized: false,
  activeView: "home",
  activeDebtTab: "receivable",
  transactions: new Map(),
  debts: new Map(),
  savingsGoals: new Map(),
  subscriptions: new Map(),
  expenseTransactions: [],
  filteredExpenseTransactions: [],
  recentTransactionsLoaded: false,
  recentLoadedTransactionIds: new Set(),
  recentLoadedTransactions: [],
  recentTransactionsCursor: null,
  recentTransactionsHasMore: false,
  recentTransactionsLoadingMore: false,
  analysisPeriod: "current",
  accountBalances: {
    yape: 0,
    efectivo: 0,
  },
  ledgerBalance: 0,
  ledgerBalanceReady: false,
  pendingAccountDebits: {
    yape: 0,
    efectivo: 0,
  },
  accountsReady: false,
  transactionsReady: false,
  subscriptionsReady: false,
  pendingSubscriptionCharges: new Set(),
  subscriptionSubmitting: false,
  privacyMode: false,
  debtAlerts: [],
  notificationsOpen: false,
  notificationPermission: "default",
  nativeNotificationShown: false,
  sheetTimers: new WeakMap(),
  confirmationResolver: null,
  confirmationTimer: null,
  maxConfirmationAmount: null,
  toastTimer: null,
  expenseChart: null,
  geminiQueueTail: Promise.resolve(),
  geminiPendingRequests: new Map(),
  geminiLastRequestAt: 0,
  geminiCooldownUntil: 0,
  geminiRequestSequence: 0,
  manualTransactionSubmitting: false,
  smartTransactionSubmitting: false,
  aiAnalysisRunning: false,
  mediaRecorder: null,
  microphoneStream: null,
  audioChunks: [],
  audioStarting: false,
  audioRecording: false,
  audioProcessing: false,
  audioStopTimer: null,
  audioRecordingSequence: 0,
  transactionDetailId: null,
  transactionDetailTrigger: null,
  pendingDebtLedgerBackfills: new Set(),
  serviceWorkerRegistrationStarted: false,
};

export { state };
